myapp/urls.py
from django.urls import path
from .myViews.ModifyView import  modify
from .myViews.AddNotes import add_note
from .myViews.StoreView import store
from .myViews.RemoveView import remove
from .myViews.LoginVew import  login_view
from .myViews.SignUpView import signUp
from .myViews.BackgroundColor import changeColor

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', login_required(add_note,login_url='/login'), name='home'),
    path('store/', login_required(store), name='store'),
    path('garbage/', login_required(remove), name='garbage'),
    path('modify/',modify, name='modify'),
    path('register/', signUp,name='register'),
    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('login')),name='logout'),
    path('change_color/',changeColor,name="changeColor"),
]

mykeep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
] 


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class AuthorManager(BaseUserManager):
    def create_user(self, email, username,password=None):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        author = self.model(email=email, username=username)
        author.set_password(password)
        author.save(using=self._db)
        return author

    def create_superuser(self, email, username, password=None):
        author = self.create_user(email, username, password)
        author.is_admin = True
        author.save(using=self._db)
        return author

class Author(AbstractBaseUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    avatar_url = models.ImageField(upload_to='avatar/',blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_social = models.BooleanField(default=False)
    objects = AuthorManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username
    
    def has_module_perms(self, app_label):
        return True
    
    def has_perm(self, perm, obj=None):
        return True

    def is_staff(self):
        return self.is_admin
    
class Note(models.Model):
    title = models.CharField(max_length=50, blank=True)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    stored = models.BooleanField(default=False)
    removed = models.BooleanField(default=False)
    background_color = models.CharField(max_length=20, blank=True)
    def __str__(self):
        return self.title

class NoteImage(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='post_images/')

    def __str__(self):
        return self.image.name  

myapp/forms.py
from django import forms
from .models import Note
from .models import Author

# from .models import CustomUser

class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = ('title', 'content')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'note-title',"placeholder":"Tiêu đề"}),
            'content': forms.Textarea(attrs={'class':'note-textarea','rows': "auto" ,"placeholder":"Tạo ghi chú"}),
        }
        labels = {
            'title': 'Tiêu đề',
            'content': 'Nội dung',
        }
    

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=100)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    image = forms.ImageField()
    def save(self):
        user = Author.objects.create_user(email=self.cleaned_data['email'],username=self.cleaned_data['username']
            ,password=self.cleaned_data['password'])
        user.avatar_url = self.cleaned_data['image']
        user.save()
        
        
    
            

# class CustomUserCreationForm(forms.ModelForm):
#     class Meta:
#         model = CustomUser
#         fields = ['username', 'password', 'email']
#         widgets = {
#             'username': forms.TextInput(attrs={'id': 'username', 'required': True, 'placeholder': 'Username'}),
#             'password': forms.TextInput(attrs={'id': 'password', 'required': True, 'placeholder': 'Password'}),
#             'email': forms.TextInput(attrs={'id': 'email', 'required': True, 'placeholder': 'Email'}),
#         }



templates/add_note.html
{% extends 'base.html' %}
{% block title %}MyKeep{% endblock %}
{% load static %}
{% if user.is_authenticated %}

{% block selectedNavbar %}     

<div class="row selectedNotes-navbar">
  <div class="col-xl-4 col-md-5 col-sm-5 col-7">
    <div><button class="turnOff">X</button></div>
    <div><h3><span>1</span> notes selected</h3></div>
  </div>
  <div class="col-xl-3 col-md-3 col-sm-4 col-5">
    <div class="color">
      <button data-tooltip="Background Color"><i class="bi bi-palette"></i></button>
      <div class="palette">
        <button class="color-1" value="rgb(255,255,255)">X</button>
        <button class="color-2" value="rgb(242, 140, 140)"></button>
        <button class="color-3" value="rgb(248, 175, 66)"></button>
        <button class="color-4" value="rgb(230, 241, 18)"></button>
        <button class="color-5" value="rgb(166, 255, 0)"></button>
        <button class="color-6" value="rgb(0, 255, 229)"></button>
        <button class="color-7" value="rgb(191, 107, 239)"></button>
        <button class="color-8" value="rgb(240, 123, 244)"></button>
        <button class="color-9" value="rgb(238, 124, 164)"></button>
      </div>
    </div>
    <button class="selectedNotes-storeBtn" data-tooltip="Important"><i class="bi bi-box-arrow-down"></i></button>
    <button class="selectedNotes-removeBtn" data-tooltip="Remove"><i class="bi bi-trash"></i></button>
  </div>
</div>
{% endblock %}    

{% block form-navbar %} 
{% if not query %} 
<div class="row add__note-container">
    <form class="note-form" method="POST" enctype="multipart/form-data" class="w-50 mx-auto">
        {% csrf_token %}
        <div class="note-content">
            <div class="note-content-images">
            </div>
            {{ form.title }}
            {{ form.content }}
            <div class="add_images_button">
              <label for="id_image" class="btn btn-secondary btn-icon custom-file-upload"><i class="bi bi-image"></i></label>
              <input type="file" name="images" multiple id="id_image" class="d-none" />
            </div>
            <div class="row features">
              <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9 col-12 form-navbar">
                <button class="form-navbar-button" type="button" data-tooltip="Notification"><i class="bi bi-bell"></i></button>
                <div class="color" id="form-color-button">
                  <input  id="form-color" name="form-color" class="d-none" />
                  <button class="form-navbar-button" type="button" data-tooltip="Background Color"><i class="bi bi-palette"></i></button>
                  <div class="palette">
                    <button type="button" class="color-1" value="rgb(255,255,255)"></button>
                    <button type="button" class="color-2" value="rgb(242, 140, 140)"></button>
                    <button type="button" class="color-3" value="rgb(248, 175, 66)"></button>
                    <button type="button" class="color-4" value="rgb(230, 241, 18)"></button>
                    <button type="button" class="color-5" value="rgb(166, 255, 0)"></button>
                    <button type="button" class="color-6" value="rgb(0, 255, 229)"></button>
                    <button type="button" class="color-7" value="rgb(191, 107, 239)"></button>
                    <button type="button" class="color-8" value="rgb(240, 123, 244)"></button>
                    <button type="button" class="color-9" value="rgb(238, 124, 164)"></button>
                  </div>
                </div>
                  <label for="id_image" class="btn btn-secondary btn-icon custom-file-upload" data-tooltip="Add images"><i class="bi bi-image"></i></label>
                  <input type="file" name="images" multiple id="id_image" class="d-none" />
                <button class="form-navbar-button" data-tooltip="Lưu trữ" type="button" id="store-btn"><i class="bi bi-box-arrow-down"></i></button>
              </div>
              <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-12 text-center"><input type="submit" value="Add" class="btn btn-primary custom-submit"></div>
            </div>
        </div>
    </form>
</div>
{% endif %}
{% endblock %}

{% block note-navbar %} 
<div class="note-navbar">
  <button class="note-navbar-button" data-tooltip="Notification"><i class="bi bi-bell"></i></button>
  <div class="color">
    <button class="note-navbar-button" data-tooltip="Background Color"><i class="bi bi-palette"></i></button>
    <div class="palette">
      <button class="color-1" value="rgb(255,255,255)"></button>
      <button class="color-2" value="rgb(242, 140, 140)"></button>
      <button class="color-3" value="rgb(248, 175, 66)"></button>
      <button class="color-4" value="rgb(230, 241, 18)"></button>
      <button class="color-5" value="rgb(166, 255, 0)"></button>
      <button class="color-6" value="rgb(0, 255, 229)"></button>
      <button class="color-7" value="rgb(191, 107, 239)"></button>
      <button class="color-8" value="rgb(240, 123, 244)"></button>
      <button class="color-9" value="rgb(238, 124, 164)"></button>
    </div>
  </div>
  <label for="note__{{ note.id }}_image" class="btn btn-secondary btn-icon custom-file-upload" data-tooltip="Add images"><i class="bi bi-image"></i></label>
  <input type="file" name="images" multiple id="note__{{ note.id }}_image" class="d-none note__id_image" />

  <form method="POST" action="{% url 'store' %}" data-tooltip="Important">
    {% csrf_token %}
    <input type="hidden" name="note_id" value="{{ note.id }}" >
    <button class="note-navbar-button" type="submit"><i class="bi bi-box-arrow-down"></i></button>
    <input type="hidden" name="current_url" class="current_url">
  </form>
  
  <form method="POST" action="{% url 'garbage' %}" data-tooltip="Remove">
    {% csrf_token %}
    <input type="hidden" name="note_id" value="{{ note.id }}" >
    <input type="hidden" name="current_url" class="current_url">
    <button class="note-navbar-button" type="submit"><i class="bi bi-trash"></i></button>
  </form>
</div>
{% endblock %}



{% block announce_panel %}
  <div class="announce_panel" id="stored">
    <p>Archived notes</p>
    <button>X</button>
  </div>

  <div class="announce_panel" id="removed">
    <p>Moved note to garbage</p>
    <button>X</button>
  </div>

  <div class="announce_panel" id="notes_removed">
    <p>Moved <span></span> notes to garbage</p>
    <button>X</button>
  </div>

  <div class="announce_panel" id="notes_stored">
    <p>Moved <span></span> notes </p>
    <button>X</button>
  </div>

  <div class="announce_panel" id="back">
    <p>Task undone</p>
  </div>
{% endblock %} 

{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Login</a>
{% endif %}


templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    

</head>

<body>
    {% block selectedNavbar %}
    {% endblock %}

    <div class="container-fluid">
        <div class="row menu">
          <div class="row menu__container">
              <div class="col-xl-3 col-lg-4 col-md-5 col-sm-12 col-12">
                <h2 style="font-style: italic; color: grey;"><img src="{% static 'images/KeepLogo.png' %}" alt="" style="width: 50px;">{{user.username}}</h2>
              </div>
              <div class="col-xl-9 col-lg-8 col-md-7 col-sm-12 col-12 menu__container-features">
                <div>
                  <form class="search-form" method="get">
                    <button id="search" type="submit" data-tooltip="Tìm kiếm">Go</button>
                    <input type="text" placeholder="Search" id="my-search" name="q" value="{{ query }}">
                  </form>
                  <button type="button" class="clear-input" data-tooltip="Xóa tìm kiếm">X</button>
                </div>
                <div>
                  <button id="refresh-btn" data-tooltip="Làm mới"><i class="bi bi-arrow-clockwise"></i></button>
                  <button data-tooltip="Chế độ danh sách"><i class="bi bi-view-list"></i></button>
                  <button data-tooltip="Cài đặt"><i class="bi bi-gear"></i></button>
                  <button data-tooltip="{{ user.username }}">
                    <img id="user_avatar" src="{% if user.is_social %}{{ user.avatar_url }}{% else %}../../media/{{ user.avatar_url }} {% endif %}" alt="#avatar">
                  </button>
                  <a href="{% url 'logout' %}"><i class="bi bi-box-arrow-right"></i></a>
                </div>
              </div>
          </div>
        </div>
        <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-3 col-sm-12 col-12 p-0">
              <div class="row sidebar">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-4 col-4 parent">
                  
                  <a href="{% url 'home' %}"><i class="bi bi-bell"></i>Your Notes</a>
                </div>
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-4 col-4 parent">
                  
                  <a href="{% url 'store' %}"><i class="bi bi-box-arrow-down"></i>Important</a>
                </div>
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-4 col-4 parent">
                  
                  <a href="{% url 'garbage' %}"><i class="bi bi-trash"></i>Garbage</a>
                </div>
              </div>
            </div>
            <div class="col p-0">
                <div class="container note__container">
                    {% block form-navbar %} 
                    {% endblock %}
                    <div class="row notes">
                        <div id="notes-container">
                            {% for note in notes %}
                            <div class="note" value="{{ note.id }}" backgroundColor="{{note.background_color}}">
                                <div class="selected" value="false">
                                  <button class="selected-btn"><i class="bi bi-check2"></i></button>
                                </div>
                                {% if note.images.all %}
                                <div class="note-images">
                                    <div class="note-image-container">
                                      {% for image in note.images.all %}
                                            <img src="{{ image.image.url }}" alt="{{ note.title }} Image" class="note-image p-1" value="{{ image.id }}">
                                      {% endfor %}
                                    </div>
                                  </div>
                                {% endif %}
                                <div class="note-info">
                                  <h5>{{ note.title }}</h5>
                                  <p>{{ note.content }}</p>
                                </div>

                                {% block note-navbar %}
                                {% endblock %}

                              </div>
                            {% empty %}
                                <p id="noNote">No notes yet.</p>
                            {% endfor %}
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% block announce_panel %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script type="module" src="{% static 'js/script.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.min.js"></script>
</body>

</html>

templates/garbage.html
{% extends 'base.html' %}
{% block title %}MyKeep{% endblock %}

{% if user.is_authenticated %}

{% block selectedNavbar %}     

<div class="row selectedNotes-navbar" id="removeNotes-navbar">
  <div class="col-xl-4 col-md-5 col-sm-5 col-7">
    <div><button class="turnOff">X</button></div>
    <div><h3><span>1</span> notes selected</h3></div>
  </div>
  <div class="col-xl-3 col-md-3 col-sm-4 col-5">
    <div class="color">
      <button data-tooltip="Chọn màu nền"><i class="bi bi-palette"></i></button>
      <div class="palette">
        <button class="color-1" value="rgb(255,255,255)">X</button>
        <button class="color-2" value="rgb(242, 140, 140)"></button>
        <button class="color-3" value="rgb(248, 175, 66)"></button>
        <button class="color-4" value="rgb(230, 241, 18)"></button>
        <button class="color-5" value="rgb(166, 255, 0)"></button>
        <button class="color-6" value="rgb(0, 255, 229)"></button>
        <button class="color-7" value="rgb(191, 107, 239)"></button>
        <button class="color-8" value="rgb(240, 123, 244)"></button>
        <button class="color-9" value="rgb(238, 124, 164)"></button>
      </div>
    </div>
    <button class="selectedNotes-recoverBtn" data-tooltip="Restore"><i class="bi bi-arrow-counterclockwise"></i></i></button>
    <button class="selectedNotes-deleteBtn" data-tooltip="Remove"><i class="bi bi-trash"></i></button>
  </div>
</div>
{% endblock %} 

{% block form-navbar %} 
<p style="font-style: italic; color: rgb(177, 174, 174); text-align: center;">Notes in the trash will be deleted after 7 days 
<button id="delete-notes" name="all">Empty the garbage</button></p>
{% endblock %}

{% block note-navbar %} 
<div class="note-navbar">
  <form method="POST" action="{% url 'garbage' %}" data-tooltip="Restore">
    {% csrf_token %}
    <input type="hidden" name="note_id" value="{{ note.id }}" >
    <input type="hidden" name="current_url" class="current_url">
    <button class="note-navbar-button" type="submit"><i class="bi bi-arrow-counterclockwise"></i></button>
  </form>
</form>
<button class="note-navbar-button" name="only" id="delete-note" data-note-id="{{ note.id }}" type="button"><i class="bi bi-trash"></i></button>
</div>
{% endblock %}


{% block announce_panel %} 

<div class="announce_panel" id="removed">
  <p>Notes restored</p>
  <button>X</button>
</div>


<div class="announce_panel" id="notes_deleted">
  <p>Removed <span></span> notes</p>
  <button>X</button>
</div>

<div class="announce_panel" id="notes_recovered">
  <p>Restored <span></span> notes</p>
  <button>X</button>
</div>

<div class="announce_panel" id="delete">
  <p>Removed note</p>
  <button>X</button>
</div>
{% endblock %} 

{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log in</a>
{% endif %}


templates/stored_notes.html
{% extends 'base.html' %}
{% block title %}MyKeep{% endblock %}
{% load static %}

{% if user.is_authenticated %}

{% block selectedNavbar %}     
<div class="row selectedNotes-navbar">
  <div class="col-xl-4 col-md-5 col-sm-5 col-7">
    <div><button class="turnOff">X</button></div>
    <div><h3><span>1</span> notes selected</h3></div>
  </div>
  <div class="col-xl-3 col-md-3 col-sm-4 col-5">
    <div class="color">
      <button data-tooltip="Chọn màu nền"><i class="bi bi-palette"></i></button>
      <div class="palette">
        <button class="color-1" value="rgb(255,255,255)">X</button>
        <button class="color-2" value="rgb(242, 140, 140)"></button>
        <button class="color-3" value="rgb(248, 175, 66)"></button>
        <button class="color-4" value="rgb(230, 241, 18)"></button>
        <button class="color-5" value="rgb(166, 255, 0)"></button>
        <button class="color-6" value="rgb(0, 255, 229)"></button>
        <button class="color-7" value="rgb(191, 107, 239)"></button>
        <button class="color-8" value="rgb(240, 123, 244)"></button>
        <button class="color-9" value="rgb(238, 124, 164)"></button>
      </div>
    </div>
    <button class="selectedNotes-storeBtn" data-tooltip="Important"><i class="bi bi-calendar-x-fill"></i></button>
    <button class="selectedNotes-removeBtn" data-tooltip="Remove"><i class="bi bi-trash"></i></button>
  </div>
</div>
{% endblock %} 
{% block note-navbar %} 
<div class="note-navbar">
  <button class="note-navbar-button" data-tooltip="Notification"><i class="bi bi-bell"></i></button>
  <div class="color">
    <button class="note-navbar-button" data-tooltip="Background Color"><i class="bi bi-palette"></i></button>
    <div class="palette">
      <button class="color-1" value="rgb(255,255,255)">X</button>
      <button class="color-2" value="rgb(242, 140, 140)"></button>
      <button class="color-3" value="rgb(248, 175, 66)"></button>
      <button class="color-4" value="rgb(230, 241, 18)"></button>
      <button class="color-5" value="rgb(166, 255, 0)"></button>
      <button class="color-6" value="rgb(0, 255, 229)"></button>
      <button class="color-7" value="rgb(191, 107, 239)"></button>
      <button class="color-8" value="rgb(240, 123, 244)"></button>
      <button class="color-9" value="rgb(238, 124, 164)"></button>
    </div>
  </div>
  <label for="note__id_image" class="btn btn-secondary btn-icon custom-file-upload" data-tooltip="Add images"><i class="bi bi-image"></i></label>
  <input type="file" name="images" multiple id="note__id_image" class="d-none" />

  <form method="POST" action="{% url 'store' %}" data-tooltip="Unimportant">
    {% csrf_token %}
    <input type="hidden" name="note_id" value="{{ note.id }}" >
    <button class="note-navbar-button" type="submit"><i class="bi bi-calendar-x-fill"></i></button>
    <input type="hidden" name="current_url" class="current_url">
  </form>
  
  <form method="POST" action="{% url 'garbage' %}" data-tooltip="Remove">
    {% csrf_token %}
    <input type="hidden" name="note_id" value="{{ note.id }}" >
    <input type="hidden" name="current_url" class="current_url">
    <button class="note-navbar-button" type="submit"><i class="bi bi-trash"></i></button>
  </form>
</div>
{% endblock %}

{% block announce_panel %} 

<div class="announce_panel" id="stored">
  <p>Unarchived note</p>
  <button>X</button>
</div>

<div class="announce_panel" id="removed">
  <p>Moved note to garbage</p>
  <button>X</button>
</div>

<div class="announce_panel" id="notes_removed">
  <p>Moved <span></span> notes to garbage</p>
  <button>X</button>
</div>

<div class="announce_panel" id="notes_stored">
  <p>Unimportant <span></span> notes </p>
  <button>X</button>
</div>
{% endblock %} 


{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log in</a>
{% endif %}
